### ISSUE TITLE
CRDs are deleted when uninstalling with helm

### ISSUE THREAD

**Issue by evyatarmeged** [otterize/intents-operator#134]
Otterize CRDs are currently managed by helm, so running `helm uninstall`  removes them and as a result, all matching CRs. This can cause network policies and Kafka ACLs created by those custom resources to be removed as well, which is not the desired behavior.

We address this in 2 separate stages:
1. Firstly, add `"helm.sh/resource-policy": keep` annotation to prevent helm for uninstalling CRDs. Merged in helm charts [PR](https://github.com/otterize/helm-charts/pull/65).
2. Move CRDs to the helm `crds` directory and out of `templates`, as helm [best practices suggest](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/).

**Comment by orishoshan** [comment]
Fixed in https://github.com/otterize/helm-charts/pull/63
