### ISSUE TITLE
Add Status field to ClientIntents

### ISSUE THREAD

**Issue by orishoshan** [otterize/intents-operator#249]
Many resources in Kubernetes have a Status field that indicates the state of the resource.

ClientIntents are reconciled and as this is done, different kinds of policies may be created (or fail to create) depending on a variety of reasons. Today, these reasons are reflected only in Kubernetes Events.

Proposal:
Add a Kubernetes Status field to ClientIntents, which has a 'UP TO DATE' field, as well as a 'ENFORCED' field for every kind of policy (e.g. network policies, Kafka ACLs, Istio policies).

When a ClientIntent begins reconciliation, its UP TO DATE field should be set to false. When reconciliation completes successfully, UP TO DATE should be set to true.

The ENFORCED fields for each kind of policy should be set to true only if the policy is being enforced, regardless of whether it's due to an error, the feature is disabled, or the intents operator is in shadow mode (meaning enforcement is disabled by default).

This should not replace the Kubernetes Events that are sent.

**Comment by aerosouund** [comment]
Hey, i wanna take on this. I will attempt to check out the code and ask here if i need more context on something

**Comment by aerosouund** [comment]
I've took a tour in the code and saw that regarding the status field the intents type definition already has an `IntentsStatus` field. an UpToDate field can be added and this field will be accessed by the `Reconcile` method implementation for each reconciler. Am i correct in this line of thinking ? let me know if there's any other part that needs to be done

and i will check as well what needs to be done for the enforced policy proposal

**Comment by aerosouund** [comment]
I've took a tour in the code and saw that regarding the status field the intents type definition already has an `IntentsStatus` field. an UpToDate field can be added and this field will be accessed by the `Reconcile` method implementation for each reconciler. Am i correct in this line of thinking ? let me know if there's any other part that needs to be done

and i will check as well what needs to be done for the enforced policy proposal

**Comment by orishoshan** [comment]
Hey @aerosouund! Yep, you're spot on. Feel free to reach out to me on Slack if you need assistance :)
Sorry for the late reply - notifications weren't set up right for this repo. Fixed it now so we get notified for issue comments as well :)

**Comment by aerosouund** [comment]
Hello @orishoshan 
Please review the PR and let me know. i also didn't know how to test this so please let me know if there's a way you'd recommend.
If you also prefer to leave the PR open until i add the enforced field

**Comment by orishoshan** [comment]
Completed in #266
