### ISSUE TITLE
Add support for marking AWS roles and policies as unused instead of deleting them upon cleanup

### ISSUE THREAD

**Issue by orishoshan** [otterize/intents-operator#366]
Users have requested to be able to configure the intents operator to not delete AWS IAM roles and policies, but instead tag them as unused, a sort of "soft delete" mode.

@omris94 please add info on how this feature will be configured

Related: https://github.com/otterize/credentials-operator/issues/112

**Comment by omris94** [comment]
See this [reply](https://github.com/otterize/credentials-operator/issues/112#issuecomment-1971350555) to the similar issue of the `credentials-operator` project.
