### ISSUE TITLE
Change namespace in intents file from a property to a suffix on the name

### ISSUE THREAD

**Issue by usarid** [otterize/intents-operator#90]
In K8s client intents files, the client indicates which service it intends to call by specifying the service's `name`; the assumption is that the target service is in the same namespace as the client. To target a service in a different namespace (of the same cluster), the client must specify the target's namespace. That is currently expressed as:
```
calls:
  - name: target-service
  - namespace: target-namespace
```
This issue proposes to keep the semantics but change the format to:
```
calls:
  - name: target-service.target-namespace
```
The new format is more aligned with how calling services is handled within and outside Kubernetes, in that it follows a DNS pattern. 

This would be a breaking change, but this early in the life of this project I feel we can still make changes like this. Holler if you disagree.

**Comment by evyatarmeged** [comment]
This was just merged in. Feel free to reopen if required.
